[package]
name = "cirulla_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cirulla_lib = { path = "../cirulla_lib" }
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
env_logger = "0.11.3"
log = "0.4.21"
