[package]
name = "cirulla_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.1"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
uuid = { version = "1.8.0", features = ["v4", "fast-rng"] }
